// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApRMaBh8LJG-u5rO9aEDljL6r_E_y8Dcc',
    appId: '1:416447534195:web:3962822698309f52e78606',
    messagingSenderId: '416447534195',
    projectId: 'pagelogin-97a4f',
    authDomain: 'pagelogin-97a4f.firebaseapp.com',
    storageBucket: 'pagelogin-97a4f.appspot.com',
    measurementId: 'G-5RG8DCXCJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6UaWxY8OdSNBoRloD5esK6ftRp24Ua1A',
    appId: '1:416447534195:android:005106bc3adaee1be78606',
    messagingSenderId: '416447534195',
    projectId: 'pagelogin-97a4f',
    storageBucket: 'pagelogin-97a4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZiGArF2vzbpC0W2nDDwlcQIQnUZ1fV9Q',
    appId: '1:416447534195:ios:0c664f8c275b18d5e78606',
    messagingSenderId: '416447534195',
    projectId: 'pagelogin-97a4f',
    storageBucket: 'pagelogin-97a4f.appspot.com',
    iosBundleId: 'com.example.pagelogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZiGArF2vzbpC0W2nDDwlcQIQnUZ1fV9Q',
    appId: '1:416447534195:ios:0c664f8c275b18d5e78606',
    messagingSenderId: '416447534195',
    projectId: 'pagelogin-97a4f',
    storageBucket: 'pagelogin-97a4f.appspot.com',
    iosBundleId: 'com.example.pagelogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApRMaBh8LJG-u5rO9aEDljL6r_E_y8Dcc',
    appId: '1:416447534195:web:ca36c50f7b6656e0e78606',
    messagingSenderId: '416447534195',
    projectId: 'pagelogin-97a4f',
    authDomain: 'pagelogin-97a4f.firebaseapp.com',
    storageBucket: 'pagelogin-97a4f.appspot.com',
    measurementId: 'G-04KGWHJ280',
  );
}
